# Our automated release process (see release.yml) creates PRs
# to bump the version in package.json.
#
# This workflow automatically approves these PRs so they can
# be merged without human intervention.

name: Auto approve bump version PR

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'duffel-bot'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
